version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      POSTGRE_CONN_URL: postgres://admin:admin@db:5432/sob?sslmode=ssl_mode
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/usr/src/app

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "8079:5432"